version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URL: "http://api.tinybrains.web.id:8004/api"
        VITE_STORAGE_HASH_KEY: "hashkey2025"
    container_name: dev-tinybrains
    restart: always
    ports:
      - "${APP_PORT:-3000}:80"