version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URL: ${VITE_API_URL}
        VITE_STORAGE_HASH_KEY: "hashkey2025"
    container_name: ${APP_NAME:-tinybrains}
    restart: always
    ports:
      - "${APP_PORT:-3000}:80"